# Generated by Django 6.0.4 on 2026-04-17 16:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_unico', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('nombre_completo', models.CharField(max_length=255)),
                ('nombre', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=150)),
                ('fecha_nacimiento', models.DateField()),
                ('ciudad', models.CharField(max_length=100)),
                ('alergias', models.JSONField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('nivel_riesgo', models.CharField(default='Medio', max_length=50)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
